name: tazkira_app
description: "A new Flutter project."
publish_to: "none"
version: 1.1.2+7

environment:
  sdk: ^3.5.2

dependencies:
  adhan: ^2.0.0+1
  cupertino_icons: ^1.0.8
  drift_flutter: ^0.2.4
  firebase_core: ^3.12.1
  firebase_remote_config: ^5.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^19.5.0
  flutter_native_splash: 2.4.4
  flutter_qiblah: ^3.1.0+1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  geocoding: ^4.0.0
  geolocator: ^13.0.4
  get: ^4.7.2
  google_fonts: ^6.2.1
  hijri: ^3.0.0
  http: ^1.5.0
  in_app_review: ^2.0.11
  in_app_update: ^4.2.5
  intl: ^0.20.2
  latlong2: ^0.9.1
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  quran_library: ^3.1.0
  screenshot: ^3.0.0
  seasonal_decor: ^1.3.5
  share_plus: 12.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  showcaseview: ^3.0.0
  timezone: ^0.10.1
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.3.1

  flutter_compass_v2: any
  device_preview: any
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/podcasts/
    - assets/icons/
    - assets/json/
    - assets/svg/
    - shorebird.yaml
